apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: https://peer-gtq5.onrender.com
    basicAuth: false
    isDefault: true
    editable: true
