apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: https://live-streaming-server.onrender.com
    basicAuth: false
    isDefault: true
    editable: true
